components
js-tasks-ru/vue-20231109_azatgt pull request #2
Opened 2023-11-20 20:20 UTC by azatgt1996

2023-11-20 20:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-24 23:47 UTC, ShGKme reviewed
Решённые задачи приняты

2023-11-24 23:47 UTC, ShGKme commented on 02-components/03-MeetupCover/components/MeetupCover.js
> +  props: ['title', 'image'],
Лучше всегда как можно подробнее описывать пропсы

2023-11-28 15:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-11-28 19:27 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  <div :class="`toast toast_${type}`">
Лучше разделять статические и динамические классы, вычисляя только вариативную часть.
```
class="toast" :class="`toast_${type}`"
```

2023-12-02 19:35 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-03 18:16 UTC, ShGKme requested changes
В `05-vue-router/01-AuthPages` требуется убрать лишний обработчик клика.

Остальные задачи приняты, но обратите внимание на комментарии.

2023-12-09 17:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-12-09 18:49 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +             :class="[`button_${variant}`, block && 'button_block']">
Здесь также можно использовать объект для привязки классов по условию.

2023-12-10 08:22 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-12-13 00:45 UTC, ShGKme approved these changes
Все задачи приняты

2023-12-13 00:50 UTC, merged